// Package rules generates AI context rule files (.cursorrules, .claude_rules)
// from analysis results to prevent future architectural drift.
package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"archscan/internal/analyzer"
)

// Generator creates AI context rule files.
type Generator struct {
	result *analyzer.Result
}

// NewGenerator creates a new rules generator.
func NewGenerator(result *analyzer.Result) *Generator {
	return &Generator{result: result}
}

// Generate creates rule files in the repo root and returns the list of created files.
func (g *Generator) Generate(repoPath string) ([]string, error) {
	var created []string

	// Generate .cursorrules
	cursorPath := filepath.Join(repoPath, ".cursorrules")
	if err := g.writeCursorRules(cursorPath); err != nil {
		return created, fmt.Errorf("writing .cursorrules: %w", err)
	}
	created = append(created, cursorPath)

	// Generate .claude_rules (CLAUDE.md)
	claudePath := filepath.Join(repoPath, "CLAUDE.md")
	if err := g.writeClaudeRules(claudePath); err != nil {
		return created, fmt.Errorf("writing CLAUDE.md: %w", err)
	}
	created = append(created, claudePath)

	return created, nil
}

func (g *Generator) writeCursorRules(path string) error {
	var sb strings.Builder

	sb.WriteString("# .cursorrules — Auto-generated by archscan\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("# Language: %s | Health Score: %d/100\n\n",
		g.result.Language, calculateScore(g.result)))

	sb.WriteString("## Project Architecture Rules\n\n")
	sb.WriteString(fmt.Sprintf("This is a **%s** project. Follow these rules strictly:\n\n", g.result.Language))

	// Language-specific base rules
	sb.WriteString(g.baseLanguageRules())
	sb.WriteString("\n")

	// Rules derived from detected violations
	sb.WriteString("## Detected Issues — Do NOT Repeat These Patterns\n\n")

	hasRules := false
	seen := map[string]bool{}

	for _, v := range g.result.Violations {
		key := string(v.Category) + v.Title
		if seen[key] {
			continue
		}
		seen[key] = true
		hasRules = true

		sb.WriteString(fmt.Sprintf("### ❌ %s\n", v.Title))
		sb.WriteString(fmt.Sprintf("**Why it's a problem:** %s\n\n", firstSentence(v.Description)))
		sb.WriteString(fmt.Sprintf("**Required behavior:** %s\n\n", v.Suggestion))
	}

	if !hasRules {
		sb.WriteString("No specific drift patterns detected. Maintain current architecture.\n\n")
	}

	sb.WriteString("## General AI Coding Guidelines\n\n")
	sb.WriteString("- Always check if a utility function already exists before creating a new one\n")
	sb.WriteString("- Never swallow errors — always handle, log, or propagate them\n")
	sb.WriteString("- Respect the existing layer boundaries — don't skip layers for convenience\n")
	sb.WriteString("- Match the naming conventions of the surrounding code exactly\n")
	sb.WriteString("- Do not introduce new dependencies without explicit user confirmation\n")
	sb.WriteString("- Prefer small, composable functions over large monolithic implementations\n")

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func (g *Generator) writeClaudeRules(path string) error {
	var sb strings.Builder

	sb.WriteString("# CLAUDE.md — Architecture Context for Claude Code\n")
	sb.WriteString(fmt.Sprintf("> Auto-generated by archscan on %s\n\n", time.Now().Format("2006-01-02")))

	sb.WriteString("## Project Overview\n\n")
	sb.WriteString(fmt.Sprintf("- **Language:** %s\n", g.result.Language))
	sb.WriteString(fmt.Sprintf("- **Source files:** %d\n", g.result.TotalFiles))
	sb.WriteString(fmt.Sprintf("- **Architecture Health:** %d/100\n\n", calculateScore(g.result)))

	sb.WriteString("## Architectural Constraints\n\n")
	sb.WriteString(g.baseLanguageRules())
	sb.WriteString("\n")

	sb.WriteString("## Known Drift Patterns (Do Not Reproduce)\n\n")

	criticals := filterBySev(g.result.Violations, analyzer.Critical)
	warnings := filterBySev(g.result.Violations, analyzer.Warning)

	if len(criticals) > 0 {
		sb.WriteString("### 🔴 Critical — Must Never Happen\n\n")
		for _, v := range criticals {
			sb.WriteString(fmt.Sprintf("- **%s**: %s → %s\n",
				v.Title, firstSentence(v.Description), v.Suggestion))
		}
		sb.WriteString("\n")
	}

	if len(warnings) > 0 {
		sb.WriteString("### 🟡 Warnings — Avoid These Patterns\n\n")
		for _, v := range warnings {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", v.Title, v.Suggestion))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Before Generating Code\n\n")
	sb.WriteString("1. Search for existing utilities/functions that accomplish the same task\n")
	sb.WriteString("2. Confirm the target layer is correct for the new code\n")
	sb.WriteString("3. Follow the naming conventions of the existing codebase\n")
	sb.WriteString("4. Handle all errors explicitly\n")
	sb.WriteString("5. Keep functions under 80 lines — extract helpers if needed\n")

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func (g *Generator) baseLanguageRules() string {
	rules := map[string]string{
		"Go": "### Go Conventions\n" +
			"- Use 'CamelCase' for exported identifiers, 'camelCase' for unexported\n" +
			"- Always return 'error' as the last return value -- never panic in library code\n" +
			"- Use fmt.Errorf to wrap errors with context\n" +
			"- Prefer table-driven tests\n" +
			"- Avoid global mutable state\n" +
			"- Use interfaces for dependencies to enable testability",

		"Python": "### Python Conventions (PEP 8)\n" +
			"- Use snake_case for functions, variables, and modules\n" +
			"- Use PascalCase for classes\n" +
			"- Use UPPER_CASE for module-level constants\n" +
			"- Always use specific exception types -- never bare 'except:'\n" +
			"- Use type hints for all function signatures\n" +
			"- Prefer dataclasses or Pydantic models over raw dicts for structured data",

		"Java": "### Java Conventions\n" +
			"- Use camelCase for methods and variables, PascalCase for classes\n" +
			"- Always handle checked exceptions explicitly -- do not swallow them\n" +
			"- Use dependency injection over static method calls\n" +
			"- Follow SOLID principles -- especially Single Responsibility\n" +
			"- Prefer interfaces for service layers",

		"TypeScript": "### TypeScript Conventions\n" +
			"- Use camelCase for variables/functions, PascalCase for types/classes\n" +
			"- Always define return types for public functions\n" +
			"- Prefer interface over type for object shapes\n" +
			"- Use unknown over any -- always narrow types before use\n" +
			"- Handle Promise rejections -- never leave unhandled promises",
	}

	if r, ok := rules[g.result.Language]; ok {
		return r
	}
	return "Follow the established conventions of the existing codebase."
}

func firstSentence(s string) string {
	if idx := strings.IndexByte(s, '.'); idx > 0 {
		return s[:idx+1]
	}
	if idx := strings.IndexByte(s, '\n'); idx > 0 {
		return s[:idx]
	}
	if len(s) > 120 {
		return s[:120] + "..."
	}
	return s
}

func filterBySev(violations []analyzer.Violation, sev analyzer.Severity) []analyzer.Violation {
	var out []analyzer.Violation
	for _, v := range violations {
		if v.Severity == sev {
			out = append(out, v)
		}
	}
	return out
}

func calculateScore(r *analyzer.Result) int {
	score := 100
	for _, v := range r.Violations {
		switch v.Severity {
		case analyzer.Critical:
			score -= 15
		case analyzer.Warning:
			score -= 5
		case analyzer.Info:
			score -= 1
		}
	}
	if score < 0 {
		score = 0
	}
	return score
}
